version: '3'
services:
  api:
    build:
      context: ./chat-api
      dockerfile:  ./Dockerfile
    ports:
      - 32770:8081
    depends_on:
      - db
  ui:
    build:
      context: ./chat-ui
      dockerfile: ./Dockerfile
    ports:
      - 3000:4000
    depends_on:
      - api
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase