services:
  api:
    build:
      context: ./chat-api
      dockerfile:  ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 32771:80
      - 32770:443
  ui:
    build:
      context: ./chat-ui
      dockerfile: ./Dockerfile
    ports:
      - 4200:4000
    depends_on:
      - api